export const GET_PLACE_SUGGEST = 'GET_PLACE_SUGGEST';
export const GET_PLACE_SUGGEST_SUCCESS = 'GET_PLACE_SUGGEST_SUCCESS';
export const GET_PLACE_SUGGEST_FAIL = 'GET_PLACE_SUGGEST_FAIL';

export const SEARCH_PLACE = 'SEARCH_PLACE';
export const SEARCH_PLACE_SUCCESS = 'SEARCH_PLACE_SUCCESS';
export const SEARCH_PLACE_FAIL = 'SEARCH_PLACE_FAIL';
